app = "conduitl2"

[env]
  PORT = "3334"
  DATA_DIR = "/data"
  SYNC_ENABLED = "true"

[[mounts]]
  source = "data"
  destination = "/data"
  initial_size = "10gb"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1gb"
  auto_extend_size_limit = "50gb"

[[vm]]
  size = "performance-1x"
  memory = "2gb"

[[services]]
  internal_port = 3334
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
