name: Build Docker & Push to Deploy Branch

on:
  push:
    branches: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: build
          fetch-depth: 0

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Set lowercase image repo
        run: echo "LOWER_REPO=${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker buildx build \
            -t ghcr.io/${{ env.LOWER_REPO }}/strfry:latest \
            --platform linux/amd64,linux/arm64 \
            --push .

      - name: Push working tree to deploy branch (for Railway)
        run: |
          git config --global user.name "railway-deploy-bot"
          git config --global user.email "bot@railway.app"
          git checkout -B deploy
          git push -f origin deploy
