name: PR Title

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
    branches: [main]

permissions:
  pull-requests: read

jobs:
  pr-title:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          types: |
            feat
            fix
            docs
            chore
            refactor
            test
            ci
            build
            perf
            revert
            spec
